const val APPCENTER_ID_DEBUG_VERIFICATION = "TODO"
const val APPCENTER_ID_DEBUG_MEASUREMENT = "TODO"
const val APPCENTER_ID_PROD_VERIFICATION = "TODO"
const val APPCENTER_ID_PROD_MEASUREMENT = "TODO"
